workflows:
  ios-release:
    name: iOS Development Build
    environment:
      flutter: stable
      xcode: "14.2"
      vars:
        BUNDLE_ID: "com.mtajerksa.mtjry"
        CERTIFICATE_URL: $CERTIFICATE_URL
        CERTIFICATE_PASSWORD: $CERTIFICATE_PASSWORD
        PROVISIONING_PROFILE_URL: $PROVISIONING_PROFILE_URL

    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build IPA
        script: |
          flutter build ipa --release --export-method development

    artifacts:
      - build/ios/ipa/*.ipa

    code_signing:
      certificates:
        - certificate_url: $CERTIFICATE_URL
          certificate_password: $CERTIFICATE_PASSWORD
      provisioning_profiles:
        - bundle_id: "com.mtajerksa.mtjry"
          provisioning_profile_url: $PROVISIONING_PROFILE_URL

    publishing:
      # Remove App Store publishing if previously configured
      # If you want to distribute the app via email or other methods:

        notify:
          success: true
          failure: true