platform :ios, '15.0'
use_frameworks!
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  load File.join(ENV['FLUTTER_ROOT'], 'packages', 'flutter_tools', 'bin', 'podhelper.rb')
  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Force all targets to deployment target = 15.0
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'

      # Remove any -G flags from all possible build settings
      config.build_settings.keys.each do |key|
        if config.build_settings[key].kind_of?(String) && config.build_settings[key].include?('-G')
          config.build_settings[key] = config.build_settings[key].gsub(/-G\b/, '')
        elsif config.build_settings[key].kind_of?(Array)
          config.build_settings[key] = config.build_settings[key].map { |value|
            value.kind_of?(String) ? value.gsub(/-G\b/, '') : value
          }
        end
      end
    end
    flutter_additional_ios_build_settings(target)
  end
end